#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function main() {
  const deployFile = path.join(__dirname, '..', 'deployments', 'sepolia', 'SafeBid.json');
  if (!fs.existsSync(deployFile)) {
    console.error('Deployment file not found:', deployFile);
    process.exit(1);
  }
  const data = JSON.parse(fs.readFileSync(deployFile, 'utf8'));
  const address = data.address;
  const abi = data.abi;

  // Write ABI to UI
  const abiOut = path.join(__dirname, '..', 'ui', 'src', 'abi', 'SafeBid.json');
  fs.writeFileSync(abiOut, JSON.stringify(abi, null, 2));
  console.log('Wrote ABI to', abiOut);

  // Write address to UI TS config to avoid relying on .env
  const addrDir = path.join(__dirname, '..', 'ui', 'src', 'config');
  if (!fs.existsSync(addrDir)) fs.mkdirSync(addrDir, { recursive: true });
  const addrTs = path.join(addrDir, 'addresses.ts');
  const tsContent = `// Auto-generated by scripts/sync_frontend.js\nexport const SAFEBID_ADDRESS = '${address}' as const;\n`;
  fs.writeFileSync(addrTs, tsContent);
  console.log('Wrote address to', addrTs, address);
}

main();
